spring:
  application:
    name: AI-Passage-Creator
  # MySQL 数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/passage
    username: root
    password: 123.com
  # session 配置
  session:
    store-type: redis
    # session 30 天过期
    timeout: 2592000
  # Redis 配置
  data:
    redis:
      host: localhost
      port: 6379
      database: 0
  ai:
    dashscope:
      api-key: ${ai.dashscope.api-key}

server:
  port: 8567
  servlet:
    context-path: /api
    # cookie 30 天过期
    session:
      cookie:
        max-age: 2592000

# springdoc-openapi 配置
springdoc:
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.ywt.passage.controller
# knife4j 接口文档配置
knife4j:
  enable: true
  setting:
    language: zh_cn
mybatis-flex:
  configuration:
    map-underscore-to-camel-case: false




